CREATE DATABASE ONLINE_CONSULTATION1; -- CREATING DATABASE

-- CREATING DOCTOR TABLE
CREATE TABLE DOCTORS(
DOCTOR_ID INT PRIMARY KEY NOT NULL,
DOCTOR_NAME VARCHAR(50),
DOCTOR_SPECIALIZATION VARCHAR(50)
); 
-- INSERT DATA INTO DOCTORS TABLE
INSERT INTO DOCTORS VALUES(1001,'NAVEEN REDDY','CARDIOLOGY'),
(1002,'PAVANI','DETERMATOLOGIST'),
(1003,'SUNIL','oRTHOPEDICS'),
(1004,'LAKSHMI','NEUROLOGY'),
(1005,'NAVEEN','PATHOLOGY'),
(1006,'SOMU','CARDIOLOGY');
SELECT *FROM DOCTORS;


///////////////////////

-- CREATION OF APPOINT MENT TABLE
CREATE TABLE APPOINTMENT(
DOCTOR_NAME VARCHAR(50) PRIMARY KEY,
PATIENT_NAME VARCHAR(50) NOT NULL,
APPOINTMENT_DATE DATE,
ROOM_NUMBER INT );

-- INSERTION OF DATA INTO APPOINTMENT TABLE
INSERT INTO APPOINTMENT VALUES('KUMAR','MADHU','2023-09-01',101),
('VISHNU','HARISH','2023-05-04',102),
('TEJAKUMAR','POOJA','2023-08-02',103),
('MANO' ,'VYSHU','2023-04-09',104),
('ANANDREDDY','PRADEEP','2023-06-03',105);
SELECT *FROM APPOINTMENT;

//////////////////////


-- CREATION OF PATIENT TABLE
CREATE TABLE PATIENT(
PATIENT_NAME VARCHAR(50) PRIMARY KEY,
PATIENT_NUMBER INT,
ADDRESS VARCHAR(50),
PATIENT_DISEASE VARCHAR(50)
);
-- INSERTING VALUES INTO PAIENT TABLE
INSERT INTO PATIENT VALUES('CHANDANA',201,'KURNOOL','BACKPAIN'),
('HEMANTH',202,'ANATAPUR','HEADACHE'),
('CHANDU',203,'VIJAYAWADA','STOMUCHPAIN'),
('DILEEP',204,'KADAPA','FEVER'),
('GOPI',205,'THIRUPATHI','CANCER');
SELECT *FROM PATIENT;

////////////////////////



-- CREATION OF REVIEW TABLE
 CREATE TABLE REVIEW(
DOCTOR_NAME VARCHAR(50),
PATIENT_NAME VARCHAR(40),
REVIEW VARCHAR(100));
-- INSERT THEE DATA INTO REVIEWS TABLE
INSERT INTO REVIEW VALUES('NAVEEN','CHANDANA','GOOD'),
('PAVANI','SUNIL','GREAT GOB'),
('DILEEP','SHANTRHAN','NICE'),
('KAVYA','SWETHA','WONDERFUL'),
('NAVYA','NAVITHA','GOOD JOB');